language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - nvm use 8

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install -o --no-interaction
  - npm install

before_script:
  - mysql -e 'create database symphony_test;'

script: npm test

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules
